// <auto-generated />
namespace LibraryManagementSystemWithEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Categoryaddedonbook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categoryaddedonbook));
        
        string IMigrationMetadata.Id
        {
            get { return "202409021037380_Category added on book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
