// <auto-generated />
namespace LibraryManagementSystemWithEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class BookremovedinBorrowedBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookremovedinBorrowedBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202408241459007_Book removed in BorrowedBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
