// <auto-generated />
namespace LibraryManagementSystemWithEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class stock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stock));
        
        string IMigrationMetadata.Id
        {
            get { return "202408241124077_stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
