//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Topic
    {
        public int SUBJECT_TOPIC_ID { get; set; }
        public string SUBJECT_TOPIC_NAME { get; set; }
        public int THES_NO { get; set; }
    
        public virtual Thesis Thesis { get; set; }
    }
}
