//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thesis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thesis()
        {
            this.Keywords = new HashSet<Keyword>();
            this.Subject_Topic = new HashSet<Subject_Topic>();
            this.Supervisors = new HashSet<Supervisor>();
        }
    
        public int THES_NO { get; set; }
        public string THES_TITLE { get; set; }
        public string THES_ABS { get; set; }
        public int AUTHOR_ID { get; set; }
        public Nullable<int> CSV_ID { get; set; }
        public int THES_YEAR { get; set; }
        public string THES_TYPE { get; set; }
        public int UNI_ID { get; set; }
        public int INS_ID { get; set; }
        public int THES_NOP { get; set; }
        public string LANG_NAME { get; set; }
        public System.DateTime THES_SUBDATE { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Co_Supervisor Co_Supervisor { get; set; }
        public virtual Institute Institute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Keyword> Keywords { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject_Topic> Subject_Topic { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supervisor> Supervisors { get; set; }
    }
}
